quartz:
    remote_scheduler: ~
    scheduler:
        store:
            uri: '%env(MONGO_DSN)%'
            managementLockCol: 'quartz_management_lock'
            calendarCol: 'quartz_calendar'
            triggerCol: 'quartz_trigger'
            firedTriggerCol: 'quartz_fired_trigger'
            jobCol: 'quartz_job'
            pausedTriggerCol: 'quartz_paused_trigger'