version: '3'

services:
  jm:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared'
    env_file: 'apps/jm/.env'
    extra_hosts:
        - "jm.loc:127.0.0.1"
    environment:
      - VIRTUAL_HOST=jm.loc
      - NGINX_WEB_ROOT=/jobs_dev/apps/jm/public
      - NGINX_PHP_FALLBACK=/index.php
      - NGINX_PHP_LOCATION=^/index\.php(/|$$)
      - APP_DEV_PERMITTED=1
      - SHELL_VERBOSITY=3

  jmq:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: 'php bin/console quartz:scheduler'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared'
    env_file: 'apps/jm/.env'
    environment:
      - SHELL_VERBOSITY=3

  jmw:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: 'php bin/wamp_server.php'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared'
    env_file: 'apps/jm/.env'
    environment:
      - SHELL_VERBOSITY=3
    extra_hosts:
        - "wamp.jm.loc:127.0.0.1"
    ports:
      - '9090:9090'

  jmc:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: 'php bin/console enqueue:consume --setup-broker --receive-timeout=10000 --time-limit="+5 minutes" --memory-limit=300'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
      - 'jmw'
      - 'jmdh'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared'
      - './docker/xdebug.ini:/etc/php/7.1/fpm/conf.d/xdebug.ini'
      - './docker/xdebug.ini:/etc/php/7.1/cli/conf.d/xdebug.ini'
    env_file: 'apps/jm/.env'
    extra_hosts:
      - "demo.jm.loc:jmdh"
    environment:
      - PHP_IDE_CONFIG=serverName=dl.dev
      - XDEBUG_CONFIG="idekey=PHPSTORM"
      - SHELL_VERBOSITY=3

  jmdq:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php queue_demo.php"
    working_dir: '/jobs_dev/apps/demo'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/demo:/jobs_dev/apps/demo'
      - './pkg/php-shared:/jobs_dev/apps/demo/vendor/comrade/shared'
      - './pkg/php-client:/jobs_dev/apps/demo/vendor/comrade/client'
    env_file: 'apps/jm/.env'

  jmdh:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php -S 0.0.0.0:80 http_demo.php"
    working_dir: '/jobs_dev/apps/demo'
    volumes:
      - './apps/demo:/jobs_dev/apps/demo'
      - './pkg/php-shared:/jobs_dev/apps/demo/vendor/comrade/shared'
      - './pkg/php-client:/jobs_dev/apps/demo/vendor/comrade/client'
    expose:
      - '80'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    extra_hosts:
        - "demo.jm.loc:127.0.0.1"
    environment:
      - VIRTUAL_HOST=demo.jm.loc
    env_file: 'apps/jm/.env'

  ui:
    build: { context: 'docker/ui' }
    restart: 'always'
    entrypoint: "ng serve --host=0.0.0.0 --port=80 --public-host=ui.jm.loc"
    working_dir: '/ui'
    volumes:
      - './apps/ui:/ui'
    ports:
      - "3000:80"
    expose:
      - "80"
    extra_hosts:
        - "ui.jm.loc:127.0.0.1"
    environment:
      - VIRTUAL_HOST=ui.jm.loc

  rabbitmq:
    image: 'rabbitmq:3.7-management'
    restart: 'always'
    environment:
      - VIRTUAL_HOST=rabbitmq.jm.loc
      - VIRTUAL_PORT=15672
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=comrade
    ports:
      - '15672:15672'

  mongo:
    image: 'mongo:3'
    restart: 'always'
    ports:
      - "27017:27017"
    volumes:
      - './shared:/shared'

  front:
    image: 'jwilder/nginx-proxy'
    restart: 'always'
    ports:
      - "80:80"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
