# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

    wamp_public_dsn: '%env(WAMP_PUBLIC_DSN)%'
    wamp_public_realm: '%env(WAMP_PUBLIC_REALM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Makasim\Yadm\ChangesCollector: '@yadm.changes_collector'

    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@event_dispatcher'

    Enqueue\Consumption\Extension\LoggerExtension:
        autowire: false
        arguments: ['@logger']
        tags:
            - {name: 'enqueue.consumption.extension', priority: 100 }

    App\Infra\Error\ErrorCollector:
        tags:
            - { name: 'kernel.event_subscriber', priority: -100 }
            - { name: 'enqueue.consumption.extension', priority: -100 }

    formapro.pvm.dal:
        class: 'Formapro\Pvm\Yadm\StandaloneTokenDAL'
        arguments:
          - '@App\Storage\ProcessExecutionStorage'
          - '@App\Storage\TokenStorage'

    formapro.pvm.token_locker:
        class: 'Formapro\Pvm\Yadm\TokenLocker'
        arguments:
            - '@yadm.token.pessimistic_lock'

    Formapro\Pvm\TokenLockerInterface: '@formapro.pvm.token_locker'

    Formapro\Pvm\DefaultBehaviorRegistry: ~

    Formapro\Pvm\BehaviorRegistry: '@Formapro\Pvm\DefaultBehaviorRegistry'
    Formapro\Pvm\DAL: '@formapro.pvm.dal'

    Formapro\Pvm\Enqueue\AsyncTransition: ~
    Formapro\Pvm\AsyncTransition: '@Formapro\Pvm\Enqueue\AsyncTransition'

    Formapro\Pvm\ProcessEngine:
        autowire: false
        arguments:
            - '@Formapro\Pvm\DefaultBehaviorRegistry'
            - '@Formapro\Pvm\DAL'
            - '@Formapro\Pvm\AsyncTransition'

    App\Infra\JsonSchema\LocalUriRetriver:
        autowire: false
        arguments:
            - '%kernel.root_dir%/../config/schemas'
            - 'http://comrade.forma-pro.com/schemas'

    JsonSchema\Uri\UriRetriever:
        autowire: false
        calls:
            - ['setUriRetriever', ['@App\Infra\JsonSchema\LocalUriRetriver']]

    JsonSchema\Constraints\Factory:
        autowire: false
        arguments:
            - ~
            - '@JsonSchema\Uri\UriRetriever'
            - 2 # JsonSchema\Constraints\Constraint::CHECK_MODE_TYPE_CAST

    App\Infra\JsonSchema\SchemaValidator: ~

    App\Queue\:
        resource: '../src/Queue/*'
        autoconfigure: true

    App\Service\:
        resource: '../src/Service/*'
        autoconfigure: false
        autowire: true

    App\Command\:
        resource: '../src/Command/*'
        autoconfigure: true
        autowire: true

    App\Pvm\Behavior\:
        resource: '../src/Pvm/Behavior/*'
        autoconfigure: true
        tags:
            - { name: 'pvm.behavior' }

    Formapro\Pvm\Enqueue\HandleAsyncTransitionProcessor:
        autowire: false
        arguments:
            - '@Formapro\Pvm\ProcessEngine'
            - '@formapro.pvm.token_locker'
            - '@logger'
        tags:
            -
                name: 'enqueue.processor'
                command: 'pvm_handle_async_transition'
                queue: 'pvm_handle_async_transition'
                prefix_queue: false
                exclusive: true

    App\Infra\Enqueue\WaitForBrokerListener:
        autowire: false
        arguments: ['%env(ENQUEUE_DSN)%', '@logger']
        tags:
            - { name: 'kernel.event_subscriber', priority: -100 }

    App\Infra\Enqueue\LimitMessageRedeliveryExtension:
        arguments:
          - '@enqueue.transport.default.context'
          - 5
        tags:
            - { name: 'enqueue.consumption.extension', priority: 100 }

    App\Service\BuildMongoIndexesService:
        autowire: false
        arguments:
            - '@yadm.client'
            - '%env(MONGO_DSN)%'

    App\Service\ChangeJobStateService: ~

    App\Api\Controller\:
        resource: '../src/Api/Controller/*'
        public: true
        tags: ['controller.service_arguments']

    App\Controller\:
        resource: '../src/Controller/*'
        public: true
        tags: ['controller.service_arguments']

    Quartz\Bridge\Scheduler\RemoteScheduler: '@quartz.remote.scheduler'

    Quartz\Scheduler\Store\YadmStoreResource: '@quartz.store_resource'

    App\Infra\ThruwayClient:
        arguments: ['%env(WAMP_DSN)%', '%env(WAMP_REALM)%']
